### PR TITLE
fixes examples

### PR DESCRIPTION
**Pull request by fsmanuel**

### CODE REVIEW

**Comment by ryanflorence** [comment]
I don't understand...

**Comment by fsmanuel** [comment]
@rpflorence looking at the [demo](http://instructure.github.io/ic-tabs/examples/basic.html) i first thought there is something wrong with the foods, cause the tab says Hamburger but the h2 is Toast. I just changed the first tab-panel h2 which i think is mistakenly Toast. Correct me if i'm wrong.

**Comment by ryanflorence** [comment]
Oh whoops, thanks :)

**Comment by fsmanuel** [comment]
sorry for not being clear about it in the first place.

**Pull request merged**
